[package]
name = "mdbx-freelist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth" }
tempfile = "3.8.1"
eyre = "0.6.8"
rand = "0.8.5"
